[alias]
dev = "run --package ruff_dev --bin ruff_dev"
benchmark = "bench -p ruff_benchmark --bench linter --bench formatter --"

[target.'cfg(target_os = "windows")']
rustflags = [
  # "-C",
  # "target-feature=+crt-static",
  "-C",
  "target-cpu=native",
  "--cfg",
  "windows_slim_errors",
]
[target.'cfg(target_os = "linux")']
rustflags = [
  "-C",
  "target-cpu=native"
]

[profile.release]
codegen-units = 1
debug = false
lto = true
opt-level = 's'
panic = "abort"
strip = true
